# 网站基本信息
title: LanteanNote | Notes-Organized
description: 一个持续进化的个人知识库。旨在系统性地记录我的想法、笔记和经验，实现知识复利。
author: "lantean"
email: "614625562@qq.com"

show_downloads: true

# URL 设置
# baseurl: ""  # 如果项目在子路径，填写子路径名
# url: "https://lantean600.github.io/LanteanNote"  # 你的域名

# 构建设置
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# markdown: kramdown  # Markdown 解析器
# permalink: pretty   # 链接格式
# timezone: Asia/Shanghai  # 时区

# 主题设置
theme: jekyll-theme-architect
# jekyll-theme-architect 
# jekyll-theme-cayman  

# # 插件（GitHub Pages 默认支持）
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-remote-theme

# # 自定义变量
# github_username: lantean600
# # twitter_username:
