# 网站基本信息
title: LanteanNote | Notes-Organized
description: 一个持续进化的个人知识库。旨在系统性地记录我的想法、笔记和经验，实现知识复利。
author: "lantean"
email: "614625562@qq.com"

show_downloads: true

# URL 设置
baseurl: "/LanteanNote"  # 如果是用户名的子仓库，必须设置！
url: "https://lantean600.github.io"  # 主域名

# 构建设置
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
# markdown: kramdown  # Markdown 解析器
# permalink: pretty   # 链接格式
# timezone: Asia/Shanghai  # 时区

# 主题设置
theme: minima
# override_theme_default_layout: false
# jekyll-theme-architect 
# jekyll-theme-cayman

# 自定义头文件（关键！）
# head_scripts:
#   - "https://polyfill.io/v3/polyfill.min.js?features=es6"
#   - "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"

# 自定义MathJax配置
mathjax:
  enable: true
  config_file: "mathjax-config.js"

# 插件（GitHub Pages 默认支持）
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-optional-front-matter

# # 自定义变量
# github_username: lantean600
# # twitter_username:
