# _config.yml

# 网站基本信息
title: LanteanNote | Notes-Organized
description: 个人知识库
author: "lantean"
baseurl: "/LanteanNote"
url: "https://lantean600.github.io"

# 构建设置
markdown: kramdown
highlighter: rouge

# 主题设置
# 关键：由于您已完全自定义了 _layouts/default.html，必须注释掉主题，否则会产生冲突。
# theme: minima
remote_theme: jekyll/minima

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 自定义站点变量（可选）
# github_username: lantean600
